// Item descriptions and chat messages, used by gen_data.js. Each entry: [english, german].
module.exports.DESC = {
  edge_detector: ['Short pulse on every change of the back input, on and off.', 'Kurzer Impuls bei jeder Änderung des Eingangs hinten, an und aus.'],
  analog_inverter: ['Outputs 15 minus the strength coming in from the back.', 'Gibt 15 minus die Stärke von hinten aus.'],
  signal_adder: ['Adds the strength from left and right (max 15).', 'Addiert die Stärke von links und rechts (max. 15).'],
  signal_subtractor: ['Back strength minus the strongest side input.', 'Stärke hinten minus stärkster Seiteneingang.'],
  item_detector: ['Outputs the number of dropped items within 5 blocks.', 'Gibt die Anzahl liegender Items in 5 Blöcken aus.'],
  light_sensor: ['Outputs the light level above it.', 'Gibt die Lichtstärke über sich aus.'],
  block_detector: ['Outputs 15 while there is a block in front of it.', 'Gibt 15 aus, solange ein Block vor ihm ist.'],
  entity_counter: ['Outputs the number of living entities within 8 blocks.', 'Gibt die Anzahl Lebewesen in 8 Blöcken aus.'],
  ice_maker: ['Freezes all water in a 5x5 area in front on each pulse.', 'Friert bei jedem Impuls alles Wasser 5x5 vor sich ein.'],
  water_pump: ['Removes water and lava in a 5x5x5 area in front on each pulse.', 'Pumpt bei jedem Impuls Wasser und Lava 5x5x5 vor sich ab.'],
  firework_launcher: ['Launches a random firework on each pulse. Needs nothing.', 'Schießt bei jedem Impuls ein zufälliges Feuerwerk. Braucht nichts.'],
  snowball_turret: ['Fires a spread of 8 snowballs on each pulse.', 'Schießt bei jedem Impuls 8 Schneebälle gestreut.'],
  anvil_dropper: ['Drops an anvil from 12 blocks above the spot 6 blocks in front.', 'Lässt einen Amboss aus 12 Blöcken Höhe auf die Stelle 6 Blöcke vor sich fallen.'],
  cluster_tnter: ['Spawns 5 primed TNT spread out in front on each pulse.', 'Setzt bei jedem Impuls 5 gezündete TNT verteilt vor sich.'],
  tnt_rain: ['Lets 9 primed TNT rain down from 20 blocks above the area in front.', 'Lässt 9 gezündete TNT aus 20 Blöcken Höhe auf den Bereich vor sich regnen.'],
  block_swapper: ['Swaps the block in front with the block behind on each pulse.', 'Tauscht bei jedem Impuls den Block vorne mit dem Block hinten.'],
  heal_pad: ['Heals everything standing on it while powered.', 'Heilt alles, was darauf steht, solange sie an ist.'],
  speed_pad: ['Gives speed to everything standing on it while powered.', 'Gibt allem darauf Tempo, solange sie an ist.'],
  smoke_emitter: ['Puffs thick smoke while powered.', 'Stößt dicken Rauch aus, solange er an ist.'],
  tnt_activator: ['Use: turns all frozen TNT within 32 blocks into live TNT.', 'Benutzen: macht alles eingefrorene TNT in 32 Blöcken scharf.'],
  tnter: ['Spawns primed TNT in front on every redstone signal. Needs no TNT.', 'Setzt bei jedem Redstone-Signal gezündetes TNT vor sich. Braucht kein TNT.'],
  freeze_tnter: ['Spawns frozen TNT: it never explodes and does not move, except by pistons and water.', 'Setzt eingefrorenes TNT: explodiert nie und bewegt sich nicht, außer durch Kolben und Wasser.'],
  activator_net: ['Frozen TNT passing through becomes normal primed TNT.', 'Eingefrorenes TNT, das hindurchgeht, wird zu normalem TNT.'],
  entity_teleporter: ['Stores every non-player entity above it exactly as it is. Release with a Remote Detonator.', 'Speichert jedes Entity (außer Spieler) über sich genau so, wie es ist. Freigabe per Fernzünder.'],
  remote_detonator: ['Right click an Entity Teleporter to link. Use: next stored entity appears 10 blocks above the block you look at. Breaks after one use.', 'Rechtsklick auf Entity-Teleporter zum Verbinden. Benutzen: nächstes Entity erscheint 10 Blöcke über dem angeschauten Block. Geht nach einer Benutzung kaputt.'],
  nuclear_repeater: ['Keeps the redstone dust connected to its output at full strength for up to 200 blocks.', 'Hält den Redstone-Staub an seinem Ausgang bis zu 200 Blöcke weit auf voller Stärke.'],
  arrow_shooter: ['Fill with arrows and Uranium Shards. Each signal fires 6 arrows at 100 blocks per tick, half a tick apart, for 1 shard.', 'Mit Pfeilen und Uranium Shards füllen. Jedes Signal schießt 6 Pfeile mit 100 Blöcken pro Tick im Halb-Tick-Abstand für 1 Shard.'],
  uranium_ore: ['Found in end stone in the End.', 'Kommt im Endstein im End vor.'],
  uranium_shard: ['Energy for the Arrow Shooter. Mined from Uranium Ore in the End.', 'Energie für den ArrowShooter. Aus Uranerz im End.'],
  enriched_uranium: ['Crafting material for the strongest machines.', 'Material für die stärksten Maschinen.'],
  redstone_circuit: ['Crafting material for almost every RedstonePlus block.', 'Material für fast alle RedstonePlus-Blöcke.'],
  uranium_block: ['Glowing constant redstone source.', 'Leuchtende, dauerhafte Redstone-Quelle.'],
  and_gate: ['Output on when left AND right input are on.', 'Ausgang an, wenn linker UND rechter Eingang an sind.'],
  or_gate: ['Output on when left OR right input is on.', 'Ausgang an, wenn linker ODER rechter Eingang an ist.'],
  xor_gate: ['Output on when exactly one side input is on.', 'Ausgang an, wenn genau ein Seiteneingang an ist.'],
  not_gate: ['Inverts the signal from the back.', 'Invertiert das Signal von hinten.'],
  nand_gate: ['Output off only when both side inputs are on.', 'Ausgang nur aus, wenn beide Seiteneingänge an sind.'],
  nor_gate: ['Output on only when both side inputs are off.', 'Ausgang nur an, wenn beide Seiteneingänge aus sind.'],
  xnor_gate: ['Output on when both side inputs are equal.', 'Ausgang an, wenn beide Seiteneingänge gleich sind.'],
  amplifier: ['Any signal from the back comes out at strength 15.', 'Jedes Signal von hinten kommt mit Stärke 15 raus.'],
  t_flip_flop: ['Every pulse from the back toggles the output.', 'Jeder Impuls von hinten schaltet den Ausgang um.'],
  rs_latch: ['Left input sets, right input resets. Remembers its state.', 'Links setzt, rechts setzt zurück. Merkt sich den Zustand.'],
  pulse_limiter: ['Turns any signal into a short 2 tick pulse.', 'Macht aus jedem Signal einen kurzen 2-Tick-Impuls.'],
  pulse_extender: ['Keeps the output on for 1-20 seconds after the input goes off. Right click to set.', 'Hält den Ausgang 1-20 Sekunden länger an. Rechtsklick zum Einstellen.'],
  delay_block: ['Repeater with 1-20 redstone ticks of delay. Right click to set.', 'Repeater mit 1-20 Redstone-Ticks Verzögerung. Rechtsklick zum Einstellen.'],
  randomizer: ['Every pulse from the back gives a random output.', 'Jeder Impuls von hinten ergibt einen zufälligen Ausgang.'],
  counter: ['Counts pulses from the back (0-15), outputs the count as strength. Side input resets.', 'Zählt Impulse von hinten (0-15) und gibt die Zahl als Stärke aus. Seiteneingang setzt zurück.'],
  sequencer: ['Every pulse moves the output: left, front, right.', 'Jeder Impuls schiebt den Ausgang weiter: links, vorne, rechts.'],
  redstone_crossing: ['Two lines cross without touching: back to front and left to right.', 'Zwei Leitungen kreuzen sich: hinten nach vorne und links nach rechts.'],
  clock: ['Pulses on its own. 1-20 redstone ticks, right click to set. A signal from the back pauses it.', 'Taktet von selbst. 1-20 Redstone-Ticks, Rechtsklick zum Einstellen. Signal von hinten pausiert.'],
  variable_source: ['Signal source with adjustable strength 1-15. Right click to set.', 'Signalquelle mit einstellbarer Stärke 1-15. Rechtsklick zum Einstellen.'],
  reinforced_redstone_block: ['Redstone block that survives any explosion.', 'Redstoneblock, der jede Explosion übersteht.'],
  wireless_transmitter: ['Sends its input on one of 16 channels. Right click to change channel.', 'Sendet sein Signal auf einem von 16 Kanälen. Rechtsklick wechselt den Kanal.'],
  wireless_receiver: ['Outputs 15 while its channel is active. Right click to change channel.', 'Gibt 15 aus, solange sein Kanal aktiv ist. Rechtsklick wechselt den Kanal.'],
  redstone_remote: ['Use: 1 second pulse on its channel. Sneak + use: change channel.', 'Benutzen: 1 Sekunde Impuls auf dem Kanal. Schleichen + Benutzen: Kanal wechseln.'],
  player_detector: ['Outputs 15 while a player is within 8 blocks.', 'Gibt 15 aus, wenn ein Spieler in 8 Blöcken ist.'],
  mob_detector: ['Outputs a signal while hostile mobs are within 8 blocks.', 'Gibt ein Signal, wenn Monster in 8 Blöcken sind.'],
  weather_sensor: ['7 while raining, 15 during thunderstorms.', '7 bei Regen, 15 bei Gewitter.'],
  night_sensor: ['Outputs 15 at night.', 'Gibt nachts 15 aus.'],
  laser_sensor: ['Invisible beam up to 32 blocks. Outputs 15 while something crosses it.', 'Unsichtbarer Strahl bis 32 Blöcke. Gibt 15 aus, wenn etwas durchläuft.'],
  block_breaker: ['Breaks the block in front on each pulse.', 'Baut bei jedem Impuls den Block vor sich ab.'],
  block_placer: ['Places blocks from its inventory in front on each pulse.', 'Setzt bei jedem Impuls Blöcke aus seinem Inventar vor sich.'],
  lightning_caller: ['Strikes lightning on the first block up to 64 blocks in front.', 'Lässt einen Blitz auf den ersten Block bis 64 Blöcke vor sich einschlagen.'],
  launch_pad: ['Throws everything on top high into the air on each pulse.', 'Schleudert bei jedem Impuls alles darauf hoch in die Luft.'],
  fan: ['Blows entities away, up to 8 blocks, while powered.', 'Bläst Entities bis 8 Blöcke weg, solange er an ist.'],
  item_magnet: ['Pulls items within 10 blocks and puts them into a container below.', 'Zieht Items in 10 Blöcken an und legt sie in einen Behälter darunter.'],
  fire_starter: ['Lights a fire in front while powered.', 'Zündet vor sich ein Feuer an, solange er an ist.'],
  spike_block: ['Hurts everything standing on it while powered.', 'Verletzt alles, was darauf steht, solange er an ist.'],
  phantom_block: ['Solid, but you can walk through it while powered.', 'Fest, aber mit Signal kann man durchlaufen.'],
  conveyor_belt: ['Moves entities on top. A redstone signal stops it.', 'Bewegt Entities obendrauf. Ein Redstone-Signal stoppt es.'],
  tnt_cannon: ['Launches primed TNT in an arc on each pulse. Needs no TNT.', 'Schießt bei jedem Impuls gezündetes TNT im Bogen. Braucht kein TNT.'],
  uranium_nuke: ['Huge explosion after 8 seconds. Lit by redstone, fire or explosions.', 'Riesige Explosion nach 8 Sekunden. Zündung per Redstone, Feuer oder Explosion.'],
  fireball_launcher: ['Shoots a ghast fireball on each pulse.', 'Schießt bei jedem Impuls einen Ghast-Feuerball.'],
  crop_harvester: ['Harvests and replants grown crops in a 5x5 area in front.', 'Erntet reife Pflanzen in 5x5 vor sich und pflanzt neu.'],
  alarm_siren: ['Loud alarm while powered.', 'Lauter Alarm, solange sie an ist.'],
  instant_lamp: ['Lamp that turns off instantly.', 'Lampe, die sofort ausgeht.'],
  inverted_lamp: ['Lit while NOT powered.', 'Leuchtet, wenn sie KEIN Signal hat.'],
  signal_display: ['Shows the incoming signal strength as a number.', 'Zeigt die ankommende Signalstärke als Zahl.'],
  landmine: ['Explodes when stepped on or powered. Sneak to walk over it.', 'Explodiert beim Betreten oder mit Signal. Schleichend kann man drüber.'],
  anti_gravity_field: ['Everything above it floats up while powered.', 'Alles darüber schwebt nach oben, solange es an ist.'],
  redstone_wrench: ['Rotates blocks. Sneak to rotate backwards.', 'Dreht Blöcke. Schleichen dreht rückwärts.'],
  multimeter: ['Right click a block to see its redstone values.', 'Rechtsklick auf einen Block zeigt seine Redstone-Werte.'],
};

module.exports.MSG = {
  delay_ticks: ['Delay: %s redstone ticks (%s game ticks)', 'Verzögerung: %s Redstone-Ticks (%s Spielticks)'],
  delay_seconds: ['Hold time: %s seconds', 'Haltezeit: %s Sekunden'],
  power: ['Signal strength: %s', 'Signalstärke: %s'],
  channel: ['Channel %s', 'Kanal %s'],
  remote_sent: ['Pulse sent on channel %s', 'Impuls auf Kanal %s gesendet'],
  teleporter_count: ['Stored entities: %s', 'Gespeicherte Entities: %s'],
  linked: ['Remote Detonator linked', 'Fernzünder verbunden'],
  not_linked: ['Not linked. Right click an Entity Teleporter first.', 'Nicht verbunden. Erst Rechtsklick auf einen Entity-Teleporter.'],
  teleporter_missing: ['The linked Entity Teleporter is gone.', 'Der verbundene Entity-Teleporter existiert nicht mehr.'],
  teleporter_empty: ['The Entity Teleporter is empty.', 'Der Entity-Teleporter ist leer.'],
  no_target: ['No block in sight (max. 256 blocks).', 'Kein Block anvisiert (max. 256 Blöcke).'],
  activated: ['%s frozen TNT activated', '%s eingefrorene TNT scharf gemacht'],
  multimeter: ['Incoming: %s | Weak out: %s | Strong out: %s | Comparator: %s', 'Eingang: %s | Schwach raus: %s | Stark raus: %s | Komparator: %s'],
};
