// Single source of truth for every block and item of RedstonePlus.
// Block: [name, shape, english, german, base colour, accent colour, label, pattern]
// shape decides model, blockstate and properties; pattern decides the surface texture style.
module.exports.BLOCKS = [
  ['tnter', 'machine', 'TnTer', 'TnTer', '#b3261e', '#f2f2f2', 'TNT', 'bands'],
  ['freeze_tnter', 'machine', 'FreezeTnter', 'FreezeTnter', '#5fb4e6', '#e8fbff', 'TNT', 'ice'],
  ['activator_net', 'net', 'Activator Net', 'Aktivator-Netz', '#ff4a3a', '#ffb0a0', '', 'net'],
  ['entity_teleporter', 'teleporter', 'Entity Teleporter', 'Entity-Teleporter', '#301844', '#d070ff', 'TP', 'swirl'],
  ['nuclear_repeater', 'gate_core', 'Nuclear Repeater', 'Nuclear Repeater', '#3a4a2a', '#7dff3a', 'NUK', 'hazard'],
  ['arrow_shooter', 'machine', 'Arrow Shooter', 'ArrowShooter', '#6b5436', '#e8e8e8', 'ARW', 'planks'],
  ['uranium_ore', 'ore', 'Uranium Ore', 'Uranerz', '#dcdca0', '#3cff3c', '', 'ore'],
  ['uranium_block', 'cube', 'Block of Uranium', 'Uranblock', '#39d839', '#eaffea', 'U', 'glow'],
  ['and_gate', 'gate', 'AND Gate', 'UND-Gatter', '#9aa0a8', '#ff2a1a', 'AND', 'smooth'],
  ['or_gate', 'gate', 'OR Gate', 'ODER-Gatter', '#a8a09a', '#ff2a1a', 'OR', 'smooth'],
  ['xor_gate', 'gate', 'XOR Gate', 'XOR-Gatter', '#a09aa8', '#ff2a1a', 'XOR', 'smooth'],
  ['not_gate', 'gate', 'NOT Gate', 'NICHT-Gatter', '#b0a8a0', '#ff2a1a', 'NOT', 'smooth'],
  ['nand_gate', 'gate', 'NAND Gate', 'NAND-Gatter', '#8f98a2', '#ff2a1a', 'NND', 'smooth'],
  ['nor_gate', 'gate', 'NOR Gate', 'NOR-Gatter', '#a2988f', '#ff2a1a', 'NOR', 'smooth'],
  ['xnor_gate', 'gate', 'XNOR Gate', 'XNOR-Gatter', '#988fa2', '#ff2a1a', 'XNR', 'smooth'],
  ['amplifier', 'gate_core', 'Signal Amplifier', 'Signalverstärker', '#8a7a5a', '#ffe040', 'AMP', 'smooth'],
  ['t_flip_flop', 'gate', 'T Flip-Flop', 'T-Flipflop', '#7a8a9a', '#40c0ff', 'TFF', 'grid'],
  ['rs_latch', 'gate', 'RS Latch', 'RS-Speicher', '#8a7a9a', '#c080ff', 'RS', 'grid'],
  ['pulse_limiter', 'gate', 'Pulse Limiter', 'Pulsbegrenzer', '#9a8a7a', '#ffa040', 'PLS', 'grid'],
  ['pulse_extender', 'gate', 'Pulse Extender', 'Pulsverlängerer', '#7a9a8a', '#40ffa0', 'EXT', 'grid'],
  ['delay_block', 'gate', 'Delay Block', 'Verzögerer', '#8a8a7a', '#ffd040', 'DLY', 'grid'],
  ['randomizer', 'gate_core', 'Randomizer', 'Zufallsgenerator', '#6a5a8a', '#ff60d0', 'RND', 'dots'],
  ['counter', 'gate', 'Counter', 'Zähler', '#5a6a8a', '#60a0ff', 'CNT', 'dots'],
  ['sequencer', 'gate', 'Sequencer', 'Sequenzer', '#5a8a6a', '#60ff90', 'SEQ', 'dots'],
  ['redstone_crossing', 'gate', 'Redstone Crossing', 'Redstone-Kreuzung', '#8a5a5a', '#ff4040', '+', 'cross'],
  ['clock', 'gate_core', 'Redstone Clock', 'Taktgeber', '#8a6a3a', '#ffc040', 'CLK', 'dots'],
  ['variable_source', 'cube', 'Variable Signal Source', 'Variable Signalquelle', '#7a1a1a', '#ffb0b0', 'VAR', 'circuit'],
  ['reinforced_redstone_block', 'cube', 'Reinforced Redstone Block', 'Verstärkter Redstoneblock', '#9c1010', '#6a6a6a', '', 'plated'],
  ['wireless_transmitter', 'antenna', 'Wireless Transmitter', 'Funksender', '#43304f', '#ff80ff', 'TX', 'rivets'],
  ['wireless_receiver', 'antenna', 'Wireless Receiver', 'Funkempfänger', '#2f434f', '#80ffff', 'RX', 'rivets'],
  ['player_detector', 'sensor', 'Player Detector', 'Spielerdetektor', '#324a5f', '#7fd0ff', 'PLR', 'rivets'],
  ['mob_detector', 'sensor', 'Mob Detector', 'Monsterdetektor', '#3f5231', '#9fff6a', 'MOB', 'rivets'],
  ['weather_sensor', 'sensor', 'Weather Sensor', 'Wettersensor', '#3d4b63', '#9fc8ff', 'WTR', 'rivets'],
  ['night_sensor', 'sensor', 'Night Sensor', 'Nachtsensor', '#1b1d33', '#e8e89a', 'NGT', 'stars'],
  ['laser_sensor', 'machine', 'Laser Sensor', 'Laserschranke', '#2a2a36', '#ff3030', 'LSR', 'rivets'],
  ['block_breaker', 'machine', 'Block Breaker', 'Blockbrecher', '#5a5a5a', '#ffcf40', 'BRK', 'cracks'],
  ['block_placer', 'machine', 'Block Placer', 'Blockplatzierer', '#4f5a4f', '#6ee06e', 'PLC', 'bricks'],
  ['lightning_caller', 'rod', 'Lightning Caller', 'Blitzbeschwörer', '#2d3f66', '#ffff66', 'ZAP', 'bolt'],
  ['launch_pad', 'pad', 'Launch Pad', 'Katapultplatte', '#45566b', '#80ff80', 'UP', 'chevron'],
  ['fan', 'fan', 'Redstone Fan', 'Ventilator', '#8a9aa6', '#ffffff', 'FAN', 'vents'],
  ['item_magnet', 'magnet', 'Item Magnet', 'Item-Magnet', '#50303a', '#ff9090', 'MAG', 'rivets'],
  ['fire_starter', 'machine', 'Fire Starter', 'Feuerzünder', '#5c2e1a', '#ff7a1a', 'IGN', 'flames'],
  ['spike_block', 'spikes', 'Spike Block', 'Stachelblock', '#3a3a3a', '#e0e0e0', '', 'plated'],
  ['phantom_block', 'phantom', 'Phantom Block', 'Phantomblock', '#6a5a8a', '#d8c8ff', 'PH', 'swirl'],
  ['conveyor_belt', 'conveyor', 'Conveyor Belt', 'Förderband', '#2b2b2b', '#f0c030', '', 'belt'],
  ['tnt_cannon', 'cannon', 'TNT Cannon', 'TNT-Kanone', '#3a3a3a', '#ff5040', 'CAN', 'plated'],
  ['uranium_nuke', 'nuke', 'Uranium Nuke', 'Uran-Atombombe', '#2f5a1c', '#e8e020', 'NUK', 'hazard'],
  ['fireball_launcher', 'cannon', 'Fireball Launcher', 'Feuerballwerfer', '#6a2410', '#ffa020', 'FIR', 'flames'],
  ['crop_harvester', 'machine', 'Crop Harvester', 'Ernteautomat', '#4d6b2a', '#f0e070', 'CRP', 'wheat'],
  ['alarm_siren', 'siren', 'Alarm Siren', 'Alarmsirene', '#6a1a1a', '#ff3030', 'SOS', 'stripes'],
  ['instant_lamp', 'lamp', 'Instant Lamp', 'Sofortlampe', '#5a3a1a', '#fff0b0', '', 'lamp'],
  ['inverted_lamp', 'lamp', 'Inverted Lamp', 'Invertierte Lampe', '#1a3a5a', '#b0f0ff', '', 'lamp'],
  ['signal_display', 'display', 'Signal Display', 'Signalanzeige', '#141414', '#ff3020', '', 'display'],
  ['landmine', 'mine', 'Landmine', 'Landmine', '#4a4a38', '#ff4040', '', 'dots'],
  ['anti_gravity_field', 'ring', 'Anti-Gravity Field', 'Antigravitationsfeld', '#28283e', '#b0a0ff', 'AGF', 'swirl'],
  // ---------- 20 new ones ----------
  ['edge_detector', 'gate', 'Edge Detector', 'Flankendetektor', '#7a7a9a', '#ff80a0', 'EDG', 'cross'],
  ['analog_inverter', 'gate', 'Analog Inverter', 'Analog-Inverter', '#9a7a7a', '#80c0ff', 'INV', 'cross'],
  ['signal_adder', 'gate', 'Signal Adder', 'Signal-Addierer', '#7a9a7a', '#ffff80', 'ADD', 'cross'],
  ['signal_subtractor', 'gate', 'Signal Subtractor', 'Signal-Subtrahierer', '#9a9a7a', '#ff8080', 'SUB', 'cross'],
  ['item_detector', 'sensor', 'Item Detector', 'Itemdetektor', '#5a4a2a', '#ffd080', 'ITM', 'rivets'],
  ['light_sensor', 'sensor', 'Light Sensor', 'Lichtsensor', '#5a5a2a', '#ffff90', 'LUX', 'stars'],
  ['block_detector', 'machine', 'Block Detector', 'Blockdetektor', '#3a4a4a', '#90ffff', 'BLK', 'rivets'],
  ['entity_counter', 'sensor', 'Entity Counter', 'Entity-Zähler', '#4a2a4a', '#ff90ff', 'ENT', 'rivets'],
  ['ice_maker', 'machine', 'Ice Maker', 'Eismaschine', '#6a8aaa', '#e0f8ff', 'ICE', 'ice'],
  ['water_pump', 'machine', 'Water Pump', 'Wasserpumpe', '#2a4a7a', '#60a0ff', 'PMP', 'waves'],
  ['firework_launcher', 'cannon', 'Firework Launcher', 'Feuerwerkswerfer', '#6a2a5a', '#ff80ff', 'FWK', 'stars'],
  ['snowball_turret', 'cannon', 'Snowball Turret', 'Schneeballgeschütz', '#c8d8e8', '#ffffff', 'SNW', 'ice'],
  ['anvil_dropper', 'machine', 'Anvil Dropper', 'Ambosswerfer', '#444448', '#b0b0b8', 'ANV', 'plated'],
  ['cluster_tnter', 'machine', 'Cluster TnTer', 'Cluster-TnTer', '#8a1a1a', '#ffd040', 'CLU', 'bands'],
  ['tnt_rain', 'machine', 'TNT Rain', 'TNT-Regen', '#6a1a3a', '#ff6060', 'RAIN', 'waves'],
  ['block_swapper', 'machine', 'Block Swapper', 'Blocktauscher', '#4a3a6a', '#c0a0ff', 'SWP', 'circuit'],
  ['heal_pad', 'pad', 'Heal Pad', 'Heilplatte', '#6a2a2a', '#ff8080', '+', 'cross'],
  ['speed_pad', 'pad', 'Speed Pad', 'Tempoplatte', '#2a5a6a', '#80ffff', '>>', 'chevron'],
  ['smoke_emitter', 'siren', 'Smoke Emitter', 'Rauchgenerator', '#505050', '#c0c0c0', 'SMK', 'waves'],
];

// Items: [name, english, german, base colour, accent colour, icon]
module.exports.ITEMS = [
  ['remote_detonator', 'Remote Detonator', 'Fernzünder'],
  ['uranium_shard', 'Uranium Shard', 'Uranium Shard'],
  ['enriched_uranium', 'Enriched Uranium', 'Angereichertes Uran'],
  ['redstone_circuit', 'Redstone Circuit', 'Redstone-Schaltkreis'],
  ['redstone_remote', 'Redstone Remote', 'Redstone-Fernbedienung'],
  ['redstone_wrench', 'Redstone Wrench', 'Redstone-Schraubenschlüssel'],
  ['multimeter', 'Multimeter', 'Multimeter'],
  ['tnt_activator', 'TNT Activator', 'TNT-Aktivator'],
];
